import connectDB from "@/lib/db";
import Product from "@/models/product";

export async function GET(req) {
    await connectDB();
    const products = await Product.find();
    await Product.deleteMany();
    await Product.insertMany([
        {
            title: "Blue T-shirt",
            description: "Comfortable cotton blue T-shirt for everyday wear.",
            price: 1000,
            category: "Clothing",
            image: "https://picsum.photos/500/300?random=1",
        },
        {
            title: "Nike Running Shoes",
            description: "Lightweight running shoes with breathable mesh.",
            price: 5200,
            category: "Footwear",
            image: "https://picsum.photos/500/300?random=2",
        },
        {
            title: "Adidas Jacket",
            description: "Warm and stylish zip-up jacket for winter.",
            price: 3500,
            category: "Clothing",
            image: "https://picsum.photos/500/300?random=3",
        },
        {
            title: "Wireless Headphones",
            description: "Noise-cancelling Bluetooth headphones with deep bass.",
            price: 7500,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=4",
        },
        {
            title: "Smart Watch",
            description: "Fitness smartwatch with heart-rate monitoring.",
            price: 8900,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=5",
        },
        {
            title: "Leather Wallet",
            description: "Premium leather wallet with multiple card slots.",
            price: 1800,
            category: "Accessories",
            image: "https://picsum.photos/500/300?random=6",
        },
        {
            title: "Gaming Mouse",
            description: "RGB gaming mouse with adjustable DPI.",
            price: 2500,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=7",
        },
        {
            title: "Office Backpack",
            description: "Water-resistant backpack with laptop compartment.",
            price: 3200,
            category: "Bags",
            image: "https://picsum.photos/500/300?random=8",
        },
        {
            title: "Bluetooth Speaker",
            description: "Portable Bluetooth speaker with powerful sound.",
            price: 4100,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=9",
        },
        {
            title: "Denim Jeans",
            description: "Slim-fit stretch denim jeans.",
            price: 2700,
            category: "Clothing",
            image: "https://picsum.photos/500/300?random=10",
        },
        {
            title: "Polarized Sunglasses",
            description: "Stylish UV-protected sunglasses.",
            price: 1500,
            category: "Accessories",
            image: "https://picsum.photos/500/300?random=11",
        },
        {
            title: "Coffee Mug",
            description: "Ceramic mug with ergonomic handle.",
            price: 600,
            category: "Home",
            image: "https://picsum.photos/500/300?random=12",
        },
        {
            title: "Mechanical Keyboard",
            description: "RGB mechanical keyboard with blue switches.",
            price: 6200,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=13",
        },
        {
            title: "White Sneakers",
            description: "Classic white sneakers for casual wear.",
            price: 4800,
            category: "Footwear",
            image: "https://picsum.photos/500/300?random=14",
        },
        {
            title: "Travel Water Bottle",
            description: "Insulated stainless steel water bottle.",
            price: 1300,
            category: "Home",
            image: "https://picsum.photos/500/300?random=15",
        },
        {
            title: "Wireless Charger",
            description: "Fast wireless charging pad.",
            price: 2200,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=16",
        },
        {
            title: "Yoga Mat",
            description: "Non-slip yoga mat for workouts.",
            price: 1900,
            category: "Fitness",
            image: "https://picsum.photos/500/300?random=17",
        },
        {
            title: "Basketball",
            description: "Professional indoor/outdoor basketball.",
            price: 2100,
            category: "Sports",
            image: "https://picsum.photos/500/300?random=18",
        },
        {
            title: "Cricket Bat",
            description: "English willow cricket bat.",
            price: 6400,
            category: "Sports",
            image: "https://picsum.photos/500/300?random=19",
        },
        {
            title: "Football",
            description: "FIFA-size training football.",
            price: 1800,
            category: "Sports",
            image: "https://picsum.photos/500/300?random=20",
        },
        {
            title: "LED Desk Lamp",
            description: "Adjustable LED desk lamp with touch controls.",
            price: 2400,
            category: "Home",
            image: "https://picsum.photos/500/300?random=21",
        },
        {
            title: "Laptop Stand",
            description: "Aluminum ergonomic laptop stand.",
            price: 2800,
            category: "Office",
            image: "https://picsum.photos/500/300?random=22",
        },
        {
            title: "USB-C Hub",
            description: "7-in-1 USB-C hub with HDMI support.",
            price: 3900,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=23",
        },
        {
            title: "External SSD 512GB",
            description: "High-speed portable SSD storage.",
            price: 9500,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=24",
        },
        {
            title: "Monitor Arm",
            description: "Adjustable monitor arm for desks.",
            price: 4700,
            category: "Office",
            image: "https://picsum.photos/500/300?random=25",
        },
        {
            title: "Bean Bag",
            description: "Comfortable bean bag chair.",
            price: 5600,
            category: "Furniture",
            image: "https://picsum.photos/500/300?random=26",
        },
        {
            title: "Air Fryer",
            description: "Healthy cooking air fryer with digital controls.",
            price: 12900,
            category: "Kitchen",
            image: "https://picsum.photos/500/300?random=27",
        },
        {
            title: "Electric Kettle",
            description: "1.7L stainless steel electric kettle.",
            price: 3300,
            category: "Kitchen",
            image: "https://picsum.photos/500/300?random=28",
        },
        {
            title: "Blender",
            description: "High-power kitchen blender.",
            price: 5400,
            category: "Kitchen",
            image: "https://picsum.photos/500/300?random=29",
        },
        {
            title: "Cookware Set",
            description: "Non-stick 7-piece cookware set.",
            price: 7800,
            category: "Kitchen",
            image: "https://picsum.photos/500/300?random=30",
        },
        {
            title: "Perfume",
            description: "Long-lasting premium fragrance.",
            price: 4600,
            category: "Beauty",
            image: "https://picsum.photos/500/300?random=31",
        },
        {
            title: "Face Wash",
            description: "Gentle daily face cleanser.",
            price: 850,
            category: "Beauty",
            image: "https://picsum.photos/500/300?random=32",
        },
        {
            title: "Hair Dryer",
            description: "Fast-drying hair dryer with multiple settings.",
            price: 3600,
            category: "Beauty",
            image: "https://picsum.photos/500/300?random=33",
        },
        {
            title: "Electric Toothbrush",
            description: "Rechargeable electric toothbrush.",
            price: 4400,
            category: "Health",
            image: "https://picsum.photos/500/300?random=34",
        },
        {
            title: "Camping Tent",
            description: "4-person waterproof camping tent.",
            price: 11500,
            category: "Outdoor",
            image: "https://picsum.photos/500/300?random=35",
        },
        {
            title: "Sleeping Bag",
            description: "Warm sleeping bag for camping.",
            price: 3900,
            category: "Outdoor",
            image: "https://picsum.photos/500/300?random=36",
        },
        {
            title: "Mountain Bike Helmet",
            description: "Lightweight protective cycling helmet.",
            price: 3100,
            category: "Sports",
            image: "https://picsum.photos/500/300?random=37",
        },
        {
            title: "Power Bank 20000mAh",
            description: "Fast-charging portable power bank.",
            price: 4900,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=38",
        },
        {
            title: "Graphic Tablet",
            description: "Digital drawing tablet for designers.",
            price: 9800,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=39",
        },
        {
            title: "Noise Cancelling Earbuds",
            description: "True wireless earbuds with active noise cancellation.",
            price: 6700,
            category: "Electronics",
            image: "https://picsum.photos/500/300?random=40",
        }
    ]);

    return Response.json({ message: "Seeded successfully" });
}